backend:
  name: git-gateway
  branch: main
media_folder: "img/vehiculos"
public_folder: "img/vehiculos"
collections:
  - name: "vehiculos"
    label: "Vehículos"
    folder: "content/vehiculos"
    create: true
    slug: "{{slug}}"
fields:
  - {label: "ID Único", name: "id", widget: "string"}
  - {label: "Título", name: "title", widget: "string"}
  - {label: "Precio", name: "precio", widget: "string"}
  - {label: "Foto de Portada (Catálogo)", name: "foto", widget: "image"}
  - label: "Galería de más fotos (Detalle)"
    name: "galeria"
    widget: "list"
    field: {label: "Imagen", name: "imagen", widget: "image"}
  - {label: "Descripción", name: "descripcion", widget: "text"}
