backend:
  name: git-gateway
  branch: main
media_folder: "img"
public_folder: "/img"
collections:
  - name: "vehiculos"
    label: "Vehículos"
    folder: "content/vehiculos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título del Auto", name: "title", widget: "string"}
      - {label: "Precio", name: "precio", widget: "string"}
      - {label: "Año", name: "anio", widget: "string"}
      - {label: "Kilometraje", name: "kilometraje", widget: "string"}
      - {label: "Imagen Principal", name: "imagen", widget: "image"}
      - {label: "Descripción", name: "descripcion", widget: "text"}
