backend:
  name: git-gateway
  branch: main
media_folder: "img/vehiculos"
public_folder: "img/vehiculos"
collections:
  - name: "vehiculos"
    label: "Vehículos"
    folder: "content"
    create: true
    slug: "vehiculos"
    file: "content/vehiculos.json" # Guarda todo en un JSON unificado
    fields:
      - {label: "Marca", name: "marca", widget: "select", options: ["Ford", "Volkswagen", "Ram", "Toyota", "Jeep", "Fiat", "Chevrolet", "Peugeot", "BMW", "Mercedes-Benz", "Nissan", "Citroen", "Renault", "Mini"]}
      - {label: "Modelo", name: "modelo", widget: "string"}
      - {label: "Año", name: "anio", widget: "number"}
      - {label: "Kilometraje", name: "km", widget: "number"}
      - {label: "Estado", name: "estado", widget: "select", options: ["0km", "usado"]}
      - {label: "Foto principal", name: "foto", widget: "image"}
